### ISSUE TITLE
[Feature Request] Support for 1.20.1 (and how to activate commands during a cutscene?)

### ISSUE THREAD

**Issue by ToppyTopology** [thewinnt/Cutscene-API-Forge#4]
I just found out about your mod and the features are really promising and amazing. I tested around with the example datapack and I love how the text effects have extensive features such as sounds, formatting and custom speed/delay. Path curves and other features work really well, and I do hope for the official documentation/wiki. 

I wanted to know if 1.20.1 will be supported since some major mods are still stuck at that version. I also wanted to ask how to run commands using a cutscene. I also saw that the 1.21 fabric version of the mod crashes when launched, though I assume it is already fixed by the next update

**Comment by ToppyTopology** [comment]
sorry I just realized you dropped support for 1.20.1, I hope this can be reconsidered 🙏

**Comment by F-708** [comment]
Think twice please!
Since 1.20.1 is best modpack version for near time - it should have cutscenes lol

**Comment by F-708** [comment]
Last update for 1.20.1 :)
Think a bit about it
Your mod is single for now what will allow to create immersive packs

**Comment by thewinnt** [comment]
I am planning to make a 1.20.1 version sometime in the next two weeks or so :)

**Comment by F-708** [comment]
> I am planning to make a 1.20.1 version sometime in the next two weeks or so :)

Yayyayayayayay
I can plan to make cutscenes!!!!

**Comment by ToppyTopology** [comment]
thank you 🙏, everything works. Oh just one thing it seems that your head is visible when a cutscene is started in third person
